# .github/workflows/azure-functions-python.yml
name: Build & deploy – prospectinator-funcapp

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # ①  Installer ALLE avhengigheter rett i .python_packages
    - name: Install dependencies to .python_packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt \
            --target .python_packages/lib/site-packages

    # ②  Lag ZIP – ta med .python_packages
    - name: Create deployment package
      run: |
        zip -r release.zip . -x ".git/*"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: release.zip

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: python-app

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # ③  Deploy ZIP-filen til Function App
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: prospectinator-funcapp
        package: release.zip        # ← pek direkte på zip-filen
